#!/usr/bin/env python3
"""
GH Archive - AI-authorship signal parser (proof of concept, v3)
===============================================================

Reads a GH Archive file (one JSON event per line, .json or .json.gz), walks the
commits and pull requests, and flags AI-authorship signals.

Signals computable from GH Archive events:
  coauthor_ai   - commit message has a `Co-authored-by:` trailer naming an AI TOOL
  coauthor_bot  - `Co-authored-by:` trailer naming a NON-AI bot (context only)
  selfadmit     - commit message prose says AI was used ("generated with ChatGPT")
  ai_agent      - a known AI coding agent is the pushing actor OR the commit author
                  (checked once per commit -> no double counting)
  bot_actor     - the pushing account is any bot (context only)
  ai_agent_pr   - a pull request opened by a known AI agent account

Not in GH Archive events (needs a follow-up GitHub API / diff call):
  dependency    - adding openai/langchain/... to a deps file (no file list here)
"""
import argparse
import csv
import gzip
import io
import json
import os
import re
from collections import Counter

# Known AI coding-agent identity STEMS (matched after normalization).
# Stems (no brackets) so they catch "<stem>[bot]" and URL-encoded "<stem>%5Bbot%5D".
AI_AGENT_STEMS = {
    "copilot-swe-agent", "github-copilot", "devin-ai-integration",
    "cursoragent", "cursor[bot]", "sweep-ai", "codegen-sh",
    "openhands-agent", "gemini-code-assist", "claude[bot]", "codex[bot]",
}
AI_TOOLS = [
    "copilot", "chatgpt", "gpt-4", "gpt4", "claude", "cursor", "devin",
    "aider", "codeium", "tabnine", "sweep", "openhands", "gemini", "codex",
    "amazon q",
]
SELFADMIT_PHRASES = [
    "generated with", "generated by", "written by ai", "ai-generated",
    "ai generated", "with ai assistance", "co-authored with ai", "used copilot",
    "using copilot", "with copilot", "via chatgpt", "with chatgpt", "prompted",
]
COAUTHOR_RE = re.compile(r"co-authored-by:\s*(.+)", re.IGNORECASE)


def normalize(s: str) -> str:
    """Lowercase and decode URL-encoded brackets so %5Bbot%5D == [bot]."""
    return (s or "").lower().replace("%5b", "[").replace("%5d", "]")


def is_ai_agent(value: str) -> bool:
    """True if a normalized login / author name / email contains a known agent stem."""
    v = normalize(value)
    return any(stem in v for stem in AI_AGENT_STEMS)


def open_any(path):
    if path.endswith(".gz"):
        return io.TextIOWrapper(gzip.open(path, "rb"), encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def commit_signals(message: str):
    msg = message or ""
    low = msg.lower()
    coauthor_ai = False
    coauthor_bot = False
    for m in COAUTHOR_RE.finditer(msg):
        line = m.group(1).lower()
        if any(t in line for t in AI_TOOLS):
            coauthor_ai = True
        elif "[bot]" in line:
            coauthor_bot = True
    return {
        "coauthor_ai": coauthor_ai,
        "coauthor_bot": coauthor_bot,
        "selfadmit_phrase": any(p in low for p in SELFADMIT_PHRASES),
        "selfadmit_toolname": any(t in low for t in AI_TOOLS),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path", help="GH Archive file (.json or .json.gz)")
    ap.add_argument("--csv", default="data/silver/gharchive_matches.csv")
    args = ap.parse_args()

    stats = Counter()
    examples = {"coauthor_ai": [], "selfadmit_phrase": [], "ai_agent": [], "ai_agent_pr": []}
    csv_rows = []

    with open_any(args.path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                stats["malformed_lines"] += 1
                continue

            stats["events_total"] += 1
            etype = ev.get("type")
            actor = (ev.get("actor") or {}).get("login", "")
            actor_is_bot = actor.endswith("[bot]")
            actor_is_agent = is_ai_agent(actor)
            created = ev.get("created_at", "")
            repo = (ev.get("repo") or {}).get("name", "")

            if etype == "PushEvent":
                stats["push_events"] += 1
                for c in (ev.get("payload") or {}).get("commits", []) or []:
                    stats["commits_total"] += 1
                    msg = c.get("message", "")
                    author = c.get("author") or {}
                    author_name = author.get("name", "")
                    author_email = author.get("email", "")

                    # --- agent check: actor OR commit author, evaluated ONCE ---
                    commit_is_agent = (
                        actor_is_agent
                        or is_ai_agent(author_name)
                        or is_ai_agent(author_email)
                    )

                    sig = commit_signals(msg)

                    if actor_is_bot:
                        stats["bot_actor_commits"] += 1
                    if commit_is_agent:
                        stats["ai_agent_commits"] += 1          # counted once per commit
                        if len(examples["ai_agent"]) < 10:
                            who = actor if actor_is_agent else author_name
                            examples["ai_agent"].append(f"{who} :: {msg[:65]}")
                    if sig["coauthor_ai"]:
                        stats["coauthor_ai"] += 1
                        if len(examples["coauthor_ai"]) < 10:
                            examples["coauthor_ai"].append(msg[:120].replace("\n", " "))
                    if sig["coauthor_bot"]:
                        stats["coauthor_bot"] += 1
                    if sig["selfadmit_phrase"]:
                        stats["selfadmit_phrase"] += 1
                        if len(examples["selfadmit_phrase"]) < 10:
                            examples["selfadmit_phrase"].append(msg[:100].replace("\n", " "))
                    if sig["selfadmit_toolname"]:
                        stats["selfadmit_toolname"] += 1

                    if sig["coauthor_ai"] or sig["selfadmit_phrase"] or commit_is_agent:
                        csv_rows.append({
                            "created_at": created, "repo": repo, "actor": actor,
                            "author_name": author_name, "sha": c.get("sha", ""),
                            "coauthor_ai": sig["coauthor_ai"],
                            "selfadmit_phrase": sig["selfadmit_phrase"],
                            "ai_agent": commit_is_agent,
                            "message": msg[:200].replace("\n", " "),
                        })

            elif etype == "PullRequestEvent":
                stats["pr_events"] += 1
                pr = (ev.get("payload") or {}).get("pull_request") or {}
                pr_author = (pr.get("user") or {}).get("login", "")
                if is_ai_agent(pr_author) or pr_author.endswith("[bot]"):
                    stats["bot_pr"] += 1
                if is_ai_agent(pr_author):
                    stats["ai_agent_pr"] += 1
                    if len(examples["ai_agent_pr"]) < 10:
                        examples["ai_agent_pr"].append(f"{pr_author} :: {pr.get('title','')[:65]}")

    # ---- report ----
    print("=" * 64)
    print(f"GH Archive AI-authorship signals  —  {args.path}")
    print("=" * 64)
    print(f"events total ............ {stats['events_total']:,}")
    print(f"  push events ........... {stats['push_events']:,}")
    print(f"  PR events ............. {stats['pr_events']:,}")
    print(f"  malformed lines ....... {stats['malformed_lines']:,}")
    print(f"commits total ........... {stats['commits_total']:,}")
    print("-" * 64)
    print("AI SIGNALS (trust these)")
    print(f"  coauthor_ai  (strong) . {stats['coauthor_ai']:,}   (AI-tool trailers only)")
    print(f"  ai_agent commits ...... {stats['ai_agent_commits']:,}   (actor OR commit author)")
    print(f"  ai_agent PRs .......... {stats['ai_agent_pr']:,}")
    print(f"  selfadmit_phrase ...... {stats['selfadmit_phrase']:,}")
    print("CONTEXT / NOISE (not AI)")
    print(f"  coauthor_bot .......... {stats['coauthor_bot']:,}   (renovate/dependabot/CI)")
    print(f"  bot_actor commits ..... {stats['bot_actor_commits']:,}")
    print(f"  bot PRs (all) ......... {stats['bot_pr']:,}")
    print(f"  selfadmit_toolname .... {stats['selfadmit_toolname']:,}   (bare tool mention, noisy)")
    if stats["commits_total"]:
        rate = 100 * (stats["coauthor_ai"] + stats["ai_agent_commits"]) / stats["commits_total"]
        print("-" * 64)
        print(f"  --> strong-signal rate  {rate:.4f}%  of commits this file")
    print("-" * 64)
    for key, label in [("coauthor_ai", "Co-authored-by AI examples"),
                       ("selfadmit_phrase", "Self-admitted examples"),
                       ("ai_agent", "AI-agent commit examples"),
                       ("ai_agent_pr", "AI-agent PR examples")]:
        if examples[key]:
            print(f"\n{label}:")
            for e in examples[key]:
                print(f"   • {e}")

    if csv_rows:
        os.makedirs(os.path.dirname(args.csv) or ".", exist_ok=True)
        with open(args.csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(csv_rows[0].keys()))
            w.writeheader()
            w.writerows(csv_rows)
        print(f"\nwrote {len(csv_rows)} matched commits -> {args.csv}")


if __name__ == "__main__":
    main()