#!/usr/bin/env python3
"""
GH Archive - AI-authorship signal parser (v4: multi-file + totals denominator)
===============================================================================

Reads GH Archive file(s) (one JSON event per line, .json or .json.gz), walks the
commits and pull requests, and flags AI-authorship signals.

Signals computable from GH Archive events:
  coauthor_ai   - commit message has a `Co-authored-by:` trailer naming an AI TOOL
  coauthor_bot  - `Co-authored-by:` trailer naming a NON-AI bot (context only)
  selfadmit     - commit message prose says AI was used ("generated with ChatGPT")
  ai_agent      - a known AI coding agent is the pushing actor OR the commit author
                  (checked once per commit -> no double counting)
  bot_actor     - the pushing account is any bot (context only)
  ai_agent_pr   - a pull request opened by a known AI agent account

Also writes totals.csv (month, n_commits, n_pr_events) — the DENOMINATOR needed
to turn match counts into an ai_share rate.

Input/output work on both local paths and s3:// (via fsspec/s3fs); paths default
under LAKE_ROOT. Not in GH Archive events (needs a follow-up GitHub API / diff
call): dependency additions (openai/langchain/...).
"""
import argparse
import csv
import io
import json
import os
import re
from collections import Counter

try:
    from dotenv import load_dotenv; load_dotenv()   # so LAKE_ROOT is set from .env
except ImportError:
    pass

import fsspec
from src.common.config import lake_path, lake_makedirs, lake_glob

# Known AI coding-agent identity STEMS (matched after normalization).
AI_AGENT_STEMS = {
    "copilot-swe-agent", "github-copilot", "devin-ai-integration",
    "cursoragent", "cursor[bot]", "sweep-ai", "codegen-sh",
    "openhands-agent", "gemini-code-assist", "claude[bot]", "codex[bot]",
}
AI_TOOLS = [
    "copilot", "chatgpt", "gpt-4", "gpt4", "claude", "cursor", "devin",
    "aider", "codeium", "tabnine", "sweep", "openhands", "gemini", "codex",
    "amazon q",
]
SELFADMIT_PHRASES = [
    "generated with", "generated by", "written by ai", "ai-generated",
    "ai generated", "with ai assistance", "co-authored with ai", "used copilot",
    "using copilot", "with copilot", "via chatgpt", "with chatgpt", "prompted",
]
COAUTHOR_RE = re.compile(r"co-authored-by:\s*(.+)", re.IGNORECASE)


def normalize(s: str) -> str:
    """Lowercase and decode URL-encoded brackets so %5Bbot%5D == [bot]."""
    return (s or "").lower().replace("%5b", "[").replace("%5d", "]")


def is_ai_agent(value: str) -> bool:
    """True if a normalized login / author name / email contains a known agent stem."""
    v = normalize(value)
    return any(stem in v for stem in AI_AGENT_STEMS)


def open_any(path):
    """Open a local or s3:// file, transparently gunzipping .gz (fsspec)."""
    return fsspec.open(path, "rt", compression="infer",
                       encoding="utf-8", errors="replace").open()


def expand_inputs(paths):
    """Expand any wildcard args via lake_glob (needed for s3:// globs, which the
    shell can't expand); pass through literal paths unchanged."""
    out = []
    for p in paths:
        out.extend(lake_glob(p) if any(ch in p for ch in "*?[") else [p])
    return out


def _write_text(path, text):
    """Write text to a local or s3:// path (fsspec), creating local dirs first."""
    lake_makedirs(os.path.dirname(path) or ".")
    with fsspec.open(path, "w", encoding="utf-8") as f:
        f.write(text)


def commit_signals(message: str):
    msg = message or ""
    low = msg.lower()
    coauthor_ai = False
    coauthor_bot = False
    for m in COAUTHOR_RE.finditer(msg):
        line = m.group(1).lower()
        if any(t in line for t in AI_TOOLS):
            coauthor_ai = True
        elif "[bot]" in line:
            coauthor_bot = True
    return {
        "coauthor_ai": coauthor_ai,
        "coauthor_bot": coauthor_bot,
        "selfadmit_phrase": any(p in low for p in SELFADMIT_PHRASES),
        "selfadmit_toolname": any(t in low for t in AI_TOOLS),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("paths", nargs="+", help="GH Archive file(s) (.json/.json.gz, local or s3://)")
    ap.add_argument("--csv", default=lake_path("silver/github/adoption/matches.csv"))
    ap.add_argument("--totals", default=lake_path("silver/github/adoption/totals.csv"))
    args = ap.parse_args()

    paths = expand_inputs(args.paths)

    stats = Counter()
    month_commits = Counter()
    month_prs = Counter()
    examples = {"coauthor_ai": [], "selfadmit_phrase": [], "ai_agent": [], "ai_agent_pr": []}
    csv_rows = []
    seen_sha = set()

    for path in paths:
        with open_any(path) as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    ev = json.loads(line)
                except json.JSONDecodeError:
                    stats["malformed_lines"] += 1
                    continue

                stats["events_total"] += 1
                etype = ev.get("type")
                actor = (ev.get("actor") or {}).get("login", "")
                actor_is_bot = actor.endswith("[bot]")
                actor_is_agent = is_ai_agent(actor)
                created = ev.get("created_at", "")
                month = created[:7]
                repo = (ev.get("repo") or {}).get("name", "")

                if etype == "PushEvent":
                    stats["push_events"] += 1
                    for c in (ev.get("payload") or {}).get("commits", []) or []:
                        sha = c.get("sha", "")
                        if sha and sha in seen_sha:
                            continue
                        if sha:
                            seen_sha.add(sha)
                        stats["commits_total"] += 1
                        month_commits[month] += 1
                        msg = c.get("message", "")
                        author = c.get("author") or {}
                        author_name = author.get("name", "")
                        author_email = author.get("email", "")

                        commit_is_agent = (
                            actor_is_agent
                            or is_ai_agent(author_name)
                            or is_ai_agent(author_email)
                        )

                        sig = commit_signals(msg)

                        if actor_is_bot:
                            stats["bot_actor_commits"] += 1
                        if commit_is_agent:
                            stats["ai_agent_commits"] += 1
                            if len(examples["ai_agent"]) < 10:
                                who = actor if actor_is_agent else author_name
                                examples["ai_agent"].append(f"{who} :: {msg[:65]}")
                        if sig["coauthor_ai"]:
                            stats["coauthor_ai"] += 1
                            if len(examples["coauthor_ai"]) < 10:
                                examples["coauthor_ai"].append(msg[:120].replace("\n", " "))
                        if sig["coauthor_bot"]:
                            stats["coauthor_bot"] += 1
                        if sig["selfadmit_phrase"]:
                            stats["selfadmit_phrase"] += 1
                            if len(examples["selfadmit_phrase"]) < 10:
                                examples["selfadmit_phrase"].append(msg[:100].replace("\n", " "))
                        if sig["selfadmit_toolname"]:
                            stats["selfadmit_toolname"] += 1

                        if sig["coauthor_ai"] or sig["selfadmit_phrase"] or commit_is_agent:
                            csv_rows.append({
                                "created_at": created, "month": month, "repo": repo,
                                "actor": actor, "author_name": author_name,
                                "sha": sha,
                                "coauthor_ai": sig["coauthor_ai"],
                                "selfadmit_phrase": sig["selfadmit_phrase"],
                                "ai_agent": commit_is_agent,
                                "message": msg[:200].replace("\n", " "),
                            })

                elif etype == "PullRequestEvent":
                    stats["pr_events"] += 1
                    month_prs[month] += 1
                    pr = (ev.get("payload") or {}).get("pull_request") or {}
                    pr_author = (pr.get("user") or {}).get("login", "")
                    if is_ai_agent(pr_author) or pr_author.endswith("[bot]"):
                        stats["bot_pr"] += 1
                    if is_ai_agent(pr_author):
                        stats["ai_agent_pr"] += 1
                        if len(examples["ai_agent_pr"]) < 10:
                            examples["ai_agent_pr"].append(f"{pr_author} :: {pr.get('title','')[:65]}")

    # ---- report ----
    print("=" * 64)
    print(f"GH Archive AI-authorship signals  —  {len(paths)} file(s)")
    print("=" * 64)
    print(f"events total ............ {stats['events_total']:,}")
    print(f"  push events ........... {stats['push_events']:,}")
    print(f"  PR events ............. {stats['pr_events']:,}")
    print(f"  malformed lines ....... {stats['malformed_lines']:,}")
    print(f"commits total ........... {stats['commits_total']:,}")
    print("-" * 64)
    print("AI SIGNALS (trust these)")
    print(f"  coauthor_ai  (strong) . {stats['coauthor_ai']:,}   (AI-tool trailers only)")
    print(f"  ai_agent commits ...... {stats['ai_agent_commits']:,}   (actor OR commit author)")
    print(f"  ai_agent PRs .......... {stats['ai_agent_pr']:,}")
    print(f"  selfadmit_phrase ...... {stats['selfadmit_phrase']:,}")
    print("CONTEXT / NOISE (not AI)")
    print(f"  coauthor_bot .......... {stats['coauthor_bot']:,}   (renovate/dependabot/CI)")
    print(f"  bot_actor commits ..... {stats['bot_actor_commits']:,}")
    print(f"  bot PRs (all) ......... {stats['bot_pr']:,}")
    print(f"  selfadmit_toolname .... {stats['selfadmit_toolname']:,}   (bare tool mention, noisy)")
    if stats["commits_total"]:
        rate = 100 * (stats["coauthor_ai"] + stats["ai_agent_commits"]) / stats["commits_total"]
        print("-" * 64)
        print(f"  --> strong-signal rate  {rate:.4f}%  of commits (all files)")
    print("-" * 64)
    for key, label in [("coauthor_ai", "Co-authored-by AI examples"),
                       ("selfadmit_phrase", "Self-admitted examples"),
                       ("ai_agent", "AI-agent commit examples"),
                       ("ai_agent_pr", "AI-agent PR examples")]:
        if examples[key]:
            print(f"\n{label}:")
            for e in examples[key]:
                print(f"   • {e}")

    # ---- write matches ----
    if csv_rows:
        buf = io.StringIO()
        w = csv.DictWriter(buf, fieldnames=list(csv_rows[0].keys()))
        w.writeheader()
        w.writerows(csv_rows)
        _write_text(args.csv, buf.getvalue())
        print(f"\nwrote {len(csv_rows)} matched commits -> {args.csv}")

    # ---- write totals (denominator) ----
    months = sorted(set(month_commits) | set(month_prs))
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["month", "n_commits", "n_pr_events"])
    for m in months:
        w.writerow([m, month_commits[m], month_prs[m]])
    _write_text(args.totals, buf.getvalue())
    print(f"wrote {len(months)} month-totals -> {args.totals}")


if __name__ == "__main__":
    main()